module.exports = {
  events: [
    {
      event: {
        type: "m.room.create",
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson:matrix.org",
        content: [Object],
        state_key: "",
        event_id: "$154928597033102QyaVj:matrix.org",
        origin_server_ts: 1549285970604,
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson:matrix.org",
        age: 1196751637
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "@henrik.johansson:matrix.org",
        rawDisplayName: "@henrik.johansson:matrix.org",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: undefined,
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722330
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: false,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        type: "m.room.member",
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson:matrix.org",
        content: [Object],
        state_key: "@henrik.johansson:matrix.org",
        event_id: "$154928597033103xHWSj:matrix.org",
        origin_server_ts: 1549285970998,
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson:matrix.org",
        age: 1196751243
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722330
      },
      target: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722330
      },
      status: null,
      error: null,
      forwardLooking: false,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        type: "m.room.power_levels",
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson:matrix.org",
        content: [Object],
        state_key: "",
        event_id: "$154928597133104hJBjD:matrix.org",
        origin_server_ts: 1549285971160,
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson:matrix.org",
        age: 1196751081
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: false,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        type: "m.room.join_rules",
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson:matrix.org",
        content: [Object],
        state_key: "",
        event_id: "$154928597133105oFLZQ:matrix.org",
        origin_server_ts: 1549285971372,
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson:matrix.org",
        age: 1196750869
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: false,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        type: "m.room.history_visibility",
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson:matrix.org",
        content: [Object],
        state_key: "",
        event_id: "$154928597133106SiyOa:matrix.org",
        origin_server_ts: 1549285971700,
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson:matrix.org",
        age: 1196750541
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: false,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        type: "m.room.guest_access",
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson:matrix.org",
        content: [Object],
        state_key: "",
        event_id: "$154928597233107GSbFA:matrix.org",
        origin_server_ts: 1549285972044,
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson:matrix.org",
        age: 1196750197
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: false,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        type: "m.room.name",
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson:matrix.org",
        content: [Object],
        state_key: "",
        event_id: "$154928597233108qGXpT:matrix.org",
        origin_server_ts: 1549285972380,
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson:matrix.org",
        age: 1196749861
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: false,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: { body: "Hello Riot!", msgtype: "m.text" },
        event_id: "$1549286514558442UhTIy:matrix.org",
        origin_server_ts: 1549286514078,
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson:matrix.org",
        age: 1196208163
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: [Object],
        event_id: "$1549287000560176NIdwA:matrix.org",
        origin_server_ts: 1549287000302,
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson:matrix.org",
        state_key: "@henrik.johansson712:matrix.org",
        type: "m.room.member",
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson:matrix.org",
        age: 1195721939
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson712:matrix.org",
        typing: false,
        name: "henrik.johansson712",
        rawDisplayName: "henrik.johansson712",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "invite",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      status: null,
      error: null,
      forwardLooking: false,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: [Object],
        event_id: "$1549287015560236eOwUo:matrix.org",
        origin_server_ts: 1549287015254,
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson712:matrix.org",
        state_key: "@henrik.johansson712:matrix.org",
        type: "m.room.member",
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson712:matrix.org",
        age: 1195706987,
        replaces_state: "$1549287000560176NIdwA:matrix.org",
        prev_content: [Object]
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson712:matrix.org",
        typing: false,
        name: "henrik.johansson712",
        rawDisplayName: "henrik.johansson712",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson712:matrix.org",
        typing: false,
        name: "henrik.johansson712",
        rawDisplayName: "henrik.johansson712",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      status: null,
      error: null,
      forwardLooking: false,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: { body: "Hello First Room!", msgtype: "m.text" },
        event_id: "$1549287121560671pbOBU:matrix.org",
        origin_server_ts: 1549287121513,
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson712:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson712:matrix.org",
        age: 1195600728
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson712:matrix.org",
        typing: false,
        name: "henrik.johansson712",
        rawDisplayName: "henrik.johansson712",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: { body: "Testing sync", msgtype: "m.text" },
        event_id: "$1549287363561630hzeQs:matrix.org",
        origin_server_ts: 1549287363005,
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson:matrix.org",
        age: 1195359236
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: { body: "Testing timestamp", msgtype: "m.text" },
        event_id: "$1549290304573341oGsnk:matrix.org",
        origin_server_ts: 1549290304319,
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson712:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson712:matrix.org",
        age: 1192417922
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson712:matrix.org",
        typing: false,
        name: "henrik.johansson712",
        rawDisplayName: "henrik.johansson712",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: { body: "Measurements are now ready.", msgtype: "m.notice" },
        event_id: "$1549293972590789JMbxv:matrix.org",
        origin_server_ts: 1549293972122,
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson:matrix.org",
        age: 1188750119
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: { body: "Measurements are now ready.", msgtype: "m.notice" },
        event_id: "$1549293973590797hQcEv:matrix.org",
        origin_server_ts: 1549293973074,
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson:matrix.org",
        age: 1188749167
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: { body: "Measurements are now ready.", msgtype: "m.notice" },
        event_id: "$1549293973590801vOoak:matrix.org",
        origin_server_ts: 1549293973543,
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson:matrix.org",
        age: 1188748698
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: { body: "Measurements are now ready.", msgtype: "m.notice" },
        event_id: "$1549293974590807MIwDv:matrix.org",
        origin_server_ts: 1549293974084,
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson:matrix.org",
        age: 1188748157
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: {
          body: "! How are the measurements going?",
          msgtype: "m.text"
        },
        event_id: "$1549295165596245nuUvG:matrix.org",
        origin_server_ts: 1549295165337,
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org",
        sender: "@henrik.johansson712:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        user_id: "@henrik.johansson712:matrix.org",
        age: 1187556904
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson712:matrix.org",
        typing: false,
        name: "henrik.johansson712",
        rawDisplayName: "henrik.johansson712",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482722329
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: { body: "Measurements are now ready.", msgtype: "m.notice" },
        event_id: "$1549295375597093maIws:matrix.org",
        origin_server_ts: 1549295375986,
        sender: "@henrik.johansson:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("04 Feb 2019")) },
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org"
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482721938
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: { body: "Measurements are now ready.", msgtype: "m.notice" },
        event_id: "$1549359453822113mRKWS:matrix.org",
        origin_server_ts: 1549359453998,
        sender: "@henrik.johansson:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("05 Feb 2019")) },
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org"
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482721938
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: { body: "Measurements are now ready.", msgtype: "m.notice" },
        event_id: "$1549359913823797KXSpS:matrix.org",
        origin_server_ts: 1549359913793,
        sender: "@henrik.johansson:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("05 Feb 2019")) },
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org"
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482721938
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: { body: "Measurements are now ready.", msgtype: "m.notice" },
        event_id: "$1549359968823971HwiuD:matrix.org",
        origin_server_ts: 1549359968230,
        sender: "@henrik.johansson:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("05 Feb 2019")) },
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org"
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482721938
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: {
          body: "Did you think they might not be the measuremnts going ?",
          msgtype: "m.notice",
          responds: {
            message: "! How are the measuremnts going?",
            sender: "@henrik.johansson712:matrix.org"
          }
        },
        event_id: "$1549367719855245klwwr:matrix.org",
        origin_server_ts: 1549367719820,
        sender: "@henrik.johansson:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("05 Feb 2019")) },
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org"
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482721938
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: {
          body: "Please tell me what's been bothering you.",
          msgtype: "m.notice"
        },
        event_id: "$1549367719855247klUpx:matrix.org",
        origin_server_ts: 1549367719827,
        sender: "@henrik.johansson:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("05 Feb 2019")) },
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org"
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482721938
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: {
          body: "IMG_20161030_161155-01.jpg",
          info: {
            h: 2610,
            mimetype: "image/jpeg",
            size: 2769859,
            thumbnail_info: {
              h: 450,
              mimetype: "image/jpeg",
              size: 200964,
              w: 800
            },
            thumbnail_url: "mxc://matrix.org/MCwohaAAHGmlvQOzAyfcuDVD",
            w: 4640
          },
          msgtype: "m.image",
          url: "mxc://matrix.org/oluLOYDwYMcZhxsqzCYvpvdR"
        },
        event_id: "$1549367719855246qHUNI:matrix.org",
        origin_server_ts: 1549367719824,
        sender: "@henrik.johansson:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("05 Feb 2019")) },
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org"
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson:matrix.org",
        typing: false,
        name: "henrik.johansson",
        rawDisplayName: "henrik.johansson",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482721938
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    },
    {
      event: {
        content: {
          body: "IMG_20161030_161155-01.jpg",
          info: {
            h: 2610,
            mimetype: "image/jpeg",
            size: 2769859,
            thumbnail_info: {
              h: 450,
              mimetype: "image/jpeg",
              size: 200964,
              w: 800
            },
            thumbnail_url: "mxc://matrix.org/MCwohaAAHGmlvQOzAyfcuDVD",
            w: 4640
          },
          msgtype: "m.image",
          url: "mxc://matrix.org/oluLOYDwYMcZhxsqzCYvpvdR"
        },
        event_id: "$1549370069864543qXXRU:matrix.org",
        origin_server_ts: 1549370069462,
        sender: "@henrik.johansson712:matrix.org",
        type: "m.room.message",
        unsigned: { age: new Date(Date.now() - new Date("05 Feb 2019")) },
        room_id: "!UHddZgulGIaYUQlwNG:matrix.org"
      },
      sender: {
        roomId: "!UHddZgulGIaYUQlwNG:matrix.org",
        userId: "@henrik.johansson712:matrix.org",
        typing: false,
        name: "henrik.johansson712",
        rawDisplayName: "henrik.johansson712",
        powerLevel: 0,
        powerLevelNorm: 0,
        user: null,
        membership: "join",
        events: [Object],
        _isOutOfBand: false,
        _modified: 1550482721939
      },
      target: null,
      status: null,
      error: null,
      forwardLooking: true,
      _pushActions: null,
      _clearEvent: {},
      _senderCurve25519Key: null,
      _claimedEd25519Key: null,
      _forwardingCurve25519KeyChain: [],
      _decryptionPromise: null,
      _retryDecryption: false
    }
  ]
};
